services:
  schedule:
    image: schedule3-service
    build:
      context: schedule
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-kb_bmstu_map_api_db}
    networks:
      - postgres
    ports:
      - 3000:3000

  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-kb_bmstu_map_api_db}
      PGDATA: /data/postgres
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-kb_bmstu_map_api_db}
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

